<?php

use Illuminate\Database\Seeder;

class T_OrdersDetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('t_orders_details')->insert([
            [
                'id' => 1,
                'product_id' => 1,
                'order_id' => 1,
                'shipment_status_id' => 1,
                'order_quantity' => 1,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'product_id' => 2,
                'order_id' => 2,
                'shipment_status_id' => 2,
                'order_quantity' => 2,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'product_id' => 3,
                'order_id' => 3,
                'shipment_status_id' => 2,
                'order_quantity' => 3,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'product_id' => 4,
                'order_id' => 4,
                'shipment_status_id' => 2,
                'order_quantity' => 4,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'product_id' => 3,
                'order_id' => 5,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'product_id' => 3,
                'order_id' => 6,
                'shipment_status_id' => 2,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'product_id' => 3,
                'order_id' => 7,
                'shipment_status_id' => 2,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'product_id' => 3,
                'order_id' => 8,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'product_id' => 3,
                'order_id' => 9,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'product_id' => 3,
                'order_id' => 10,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'product_id' => 3,
                'order_id' => 11,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'product_id' => 3,
                'order_id' => 12,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'product_id' => 3,
                'order_id' => 13,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'product_id' => 3,
                'order_id' => 14,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'product_id' => 3,
                'order_id' => 15,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'product_id' => 3,
                'order_id' => 16,
                'shipment_status_id' => 2,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'product_id' => 3,
                'order_id' => 17,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'product_id' => 3,
                'order_id' => 18,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'product_id' => 3,
                'order_id' => 19,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'product_id' => 3,
                'order_id' => 20,
                'shipment_status_id' => 1,
                'order_quantity' => 10,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'product_id' => 3,
                'order_id' => 1,
                'shipment_status_id' => 1,
                'order_quantity' => 7,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'product_id' => 4,
                'order_id' => 1,
                'shipment_status_id' => 1,
                'order_quantity' => 15,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'product_id' => 5,
                'order_id' => 1,
                'shipment_status_id' => 1,
                'order_quantity' => 5,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'product_id' => 1,
                'order_id' => 4,
                'shipment_status_id' => 2,
                'order_quantity' => 3,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'product_id' => 2,
                'order_id' => 4,
                'shipment_status_id' => 2,
                'order_quantity' => 8,
                'shipment_date' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
